### PR TITLE
Make time limits for search queries configurable

### PR DESCRIPTION
**Pull request by ananjaykumar2**
This PR introduces configurable time limits for async and normal queries. The allowed query days can now be managed directly through the config file.

**Note** : Updates to the config file require changes in Jenkins and master pipeline as well."

### CODE REVIEW

**Comment by ananjaykumar2** [comment]
retest this please

**Comment by ananjaykumar2** [comment]
retest this please

**Comment by ananjaykumar2** [comment]
retest this please

**Comment by ankitmashu** [comment]
retest this please

**Review by ankitmashu — APPROVED** [review]
LGTM

**Pull request merged**
